services:
  hmi-frontend:
    image: ghcr.io/elor170/hmi-frontend:latest
    container_name: hmi-frontend
    environment:
      - VITE_STREAMER_SERVER=http://$SERVER_IP:$STREAMER_BACKEND_PORT
      - VITE_STREAMER_LOGGER=http://$SERVER_IP:$STREAMER_LOGGER_PORT
      - VITE_WATERFALL_BACKEND_URL=http://$SERVER_IP:$WATERFALL_BACKEND_PORT
      - VITE_WATERFALL_STREAMER_URL=http://$SERVER_IP:$WATERFALL_STREAMER_PORT
      - VITE_3D_GAME_SERVER=http://localhost:$GAME_PORT
    ports:
      - "${HMI_FRONTEND_PORT}:80"
    networks:
      - hmi_frontend_network
    restart: always

  3d-game:
    image: ghcr.io/elor170/game-server:latest
    container_name: hmi-game
    ports: 
      - ${GAME_PORT}:80
    networks:
      - hmi_frontend_network
    restart: always

networks:
  hmi_frontend_network:
    driver: bridge

