services:
  streamer:
    build:
      context: .
      dockerfile: .docker/Dockerfile.streamer
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://hmi-mongo-db:27017
    ports:
      - "3001:3001"
    networks:
      - hmi_network
    depends_on:
      - hmi-mongo-db

  waterfall:
    build:
      context: .
      dockerfile: .docker/Dockerfile.waterfall
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - hmi_network

    depends_on:
      - hmi-mongo-db

  hmi-mongo-db:
    image: mongo:latest
    container_name: hmi-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ~/db:/data/db

    networks:
      - hmi_network

networks:
  hmi_network:
    driver: bridge
