services:
  streamer:
    build:
      context: .
      dockerfile: .docker/Dockerfile.streamer
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - hmi_network

  waterfall:
    build:
      context: .
      dockerfile: .docker/Dockerfile.waterfall
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - hmi_network

    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/db:/data/db

    networks:
      - hmi_network

networks:
  hmi_network:
    driver: bridge
