services:
  streamer:
    build:
      context: ./streamer-backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - dakar_network

  waterfall:
    build:
      context: ./waterfall-backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - dakar_network

    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    # restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db

    networks:
      - dakar_network

networks:
  dakar_network:
    driver: bridge
