services:
  hmi-frontend:
    image: ghcr.io/elor170/hmi-frontend:latest
    container_name: hmi-frontend
    environment:
      VITE_STREAMER_SERVER: http://${SERVER_IP}:${STREAMER_BACKEND_PORT}
      VITE_STREAMER_LOGGER: http://$SERVER_IP:${VITE_STREAMER_LOGGER_PORT}
      VITE_WATERFALL_BACKEND_URL: http://${SERVER_IP}:${WATERFALL_BACKEND_PORT}
      VITE_3D_GAME_SERVER: http://${FRONTEND_IP}:${GAME_PORT}
      VITE_MAPS_SERVER_URL: ${MAPS_SERVER_URL}
      PORT: $HMI_FRONTEND_PORT
    ports:
      - "${HMI_FRONTEND_PORT}:80"
    networks:
      - hmi_frontend_network
    restart: always

  3d-game:
    image: ghcr.io/elor170/game-server:latest
    container_name: hmi-game
    ports: 
      - ${GAME_PORT}:80
    networks:
      - hmi_frontend_network
    restart: always

networks:
  hmi_frontend_network:
    driver: bridge

