services:
  video-streamer:
    image: ghcr.io/elor170/streamer-server:latest
    container_name: hmi-video-streamer
    ports:
      - "$STREAMER_BACKEND_PORT:$STREAMER_BACKEND_PORT"

    networks:
      - hmi_network
    restart: always

  
  streamer-logger:
    image: ghcr.io/elor170/streamer-server:latest
    container_name: hmi-streamer-logger
    environment:
      - PORT=$STREAMER_BACKEND_PORT
      - MONGO_URI=$MONGO_URI
    ports:
      - "$STREAMER_LOGGER_PORT:$STREAMER_LOGGER_PORT"
    depends_on:
    - hmi-mongo-db
    - hmi-video-streamer
    networks:
      - hmi_network
    restart: always

  waterfall-backend:
    image: ghcr.io/elor170/waterfall-backend:latest
    container_name: hmi-waterfall-backend
    environment:
      RABBITMQ_HOST: $RABBITMQ_HOST
      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS
      PORT: $WATERFALL_BACKEND_PORT
      WATERFALL_QUEUE: $WATERFALL_QUEUE
    ports:
      - "$WATERFALL_BACKEND_PORT:$WATERFALL_BACKEND_PORT"
    depends_on:
      - hmi-rabbitmq
    networks:
      - hmi_network
    restart: always


  game-server:
    image: ghcr.io/elor170/game-server:latest
    container_name: hmi-game-server
    environment:
      MONGO_URI: $MONGO_URI
    ports:
      - "$WATERFALL_BACKEND_PORT:80"
    depends_on:
      - hmi-mongo=db
    networks:
      - hmi_network
    restart: always

  waterfall-streamer:
    image: ghcr.io/elor170/waterfall-streamer:latest
    container_name: hmi-waterfall-streamer
    environment:
      RABBITMQ_HOST: $RABBITMQ_HOST
      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS
      PORT: $WATERFALL_STREAMER_PORT
      WATERFALL_QUEUE: $WATERFALL_QUEUE
    ports:
      - "$WATERFALL_STREAMER_PORT:$WATERFALL_STREAMER_PORT"
    depends_on:
      - hmi-rabbitmq
    networks:
      - hmi_network
    restart: always

  hmi-mongo-db:
    image: mongo:latest
    container_name: hmi-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ~/db:/data/db
    networks:
      - hmi_network
    restart: always

  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: hmi-mongo-db
      ME_CONFIG_MONGODB_URL: hmi-mongo-db:27017/
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - hmi-mongo-db
    networks:
      - hmi_network

  hmi-rabbitmq:
    image: rabbitmq:management
    container_name: hmi-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
    restart: always
    ports:
      - "15671:15671"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    networks:
      - hmi_network

networks:
  hmi_network:
    driver: bridge