services:
  hmi-frontend:
    image: ghcr.io/elor170/hmi-frontend:latest
    container_name: hmi-frontend
    environment:
      MY_APP_STREAMER_SERVER: http://${SERVER_IP}:${STREAMER_BACKEND_PORT}
      MY_APP_STREAMER_LOGGER: http://$SERVER_IP:${STREAMER_LOGGER_PORT}
      MY_APP_WATERFALL_BACKEND_URL: http://${SERVER_IP}:${WATERFALL_BACKEND_PORT}
      MY_APP_WATERFALL_STREAMER_URL: http://${SERVER_IP}:${WATERFALL_STREAMER_PORT}
      MY_APP_3D_GAME_SERVER: http://${FRONTEND_IP}:${GAME_PORT}
      MY_APP_MAPS_SERVER_URL: ${MAPS_SERVER_URL}
    ports:
      - "3000:80"
    networks:
      - hmi_frontend_network
    restart: always

networks:
  hmi_frontend_network:
    driver: bridge

