packages:
  - 'packages/*'
  - "libs/*"

catalog:
  express: ^4.19.2
  typescript: 5.6.3
  body-parser: ^1.20.2
  cors: ^2.8.5
  dotenv: 16.4.5
  mongodb: ^6.8.0
  socket.io: 4.8.1
  tsx: ^4.16.2
  amqplib: 0.10.4
  '@types/amqplib': 0.10.5
  '@types/express': 4.17.21
  '@types/cors': 2.8.17
  '@types/node': 22.9.0