FROM node:20-slim

WORKDIR /app/global-types

COPY packages/global-types/package*.json ./
RUN npm install

COPY global-types ./

WORKDIR /app/service

COPY packages/waterfall-backend/package*.json ./

RUN npm install

COPY waterfall-simulator ./

RUN npm run build

ENV PORT=3002

EXPOSE $PORT

CMD ["npm", "start"]