FROM node:20-slim

WORKDIR /app/hmi-helper

COPY packages/hmi-helper/package*.json ./
RUN npm install

COPY hmi-helper ./

WORKDIR /app/service

COPY packages/waterfall-backend/package*.json ./

RUN npm install

COPY waterfall-simulator ./

RUN npm run build

ENV PORT=3002

EXPOSE $PORT

CMD ["npm", "start"]