FROM node:20-slim

RUN corepack enable pnpm && corepack use pnpm

WORKDIR /app
COPY pnpm-workspace.yaml .

WORKDIR /app/packages/global-types

COPY packages/global-types ./
RUN pnpm install

WORKDIR /app/packages/service

COPY packages/waterfall-backend ./

RUN pnpm install
RUN pnpm run build

ENV PORT=3002

EXPOSE $PORT

CMD ["pnpm", "start"]