FROM node:20-slim

WORKDIR /app/hmi-helper

COPY packages/hmi-helper/package*.json ./
RUN npm install

COPY hmi-helper ./

WORKDIR /app/service

COPY packages/streamer-backend/package*.json ./

RUN npm install

COPY streamer-backend ./

RUN npm run build

ENV PORT=3001
ENV MONGO_URI=mongodb://localhost:27017

EXPOSE $PORT

CMD ["npm", "start"]