FROM node:20-slim
ARG ServiceName

WORKDIR /app/libs/hmi-helper
COPY libs/hmi-helper .

WORKDIR /app/packages/service
COPY packages/$ServiceName ./

WORKDIR /app
RUN corepack enable
RUN corepack use pnpm
COPY pnpm-*.yaml .
COPY tsconfig.*.json .
RUN pnpm i

WORKDIR /app/packages/service
RUN pnpm i typescript
RUN pnpm build

CMD pnpm start