FROM node:20-slim

WORKDIR /app/global-types

COPY global-types/package*.json ./
RUN npm install

COPY global-types ./

WORKDIR /app/service

COPY streamer-backend/package*.json ./

RUN npm install

COPY streamer-backend ./

RUN npm run build

ENV PORT=3000
ENV MONGO_URI=mongodb://localhost:27017

EXPOSE $PORT

CMD ["npm", "start"]