FROM node:22-slim AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack use pnpm
ARG ServiceName

WORKDIR /app
COPY pnpm-*.yaml ./
COPY tsconfig.*.json ./

COPY libs/hmi-helper ./libs/hmi-helper
COPY /packages/$ServiceName ./packages/$ServiceName
RUN pnpm install

WORKDIR /app/packages/$ServiceName
RUN pnpm build
CMD [ "pnpm", "start" ]