FROM node:22-alpine AS build
ARG ServiceName

WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack use pnpm@9
COPY pnpm-*.yaml ./
COPY tsconfig.*.json .

COPY libs/hmi-helper ./libs/hmi-helper
COPY /packages/$ServiceName ./packages/$ServiceName
RUN pnpm install
RUN pnpm --filter $ServiceName build

WORKDIR /app/packages/$ServiceName
CMD [ "pnpm", "start" ]