FROM node:20-slim

WORKDIR /app/packages/hmi-helper
COPY packages/hmi-helper .

WORKDIR /app/packages/service
COPY packages/hmi-frotend ./

WORKDIR /app
RUN corepack enable
RUN corepack use pnpm
COPY pnpm-workspace.yaml .
RUN pnpm i

WORKDIR /app/packages/service
RUN pnpm i typescript

CMD pnpm build && pnpm start