FROM node:20-slim

WORKDIR /app/global-types

COPY global-types/package*.json ./
RUN npm install

COPY global-types ./

WORKDIR /app/service

COPY waterfall-backend/package*.json ./

RUN npm install

COPY waterfall-backend ./

RUN npm run build

ENV PORT=3000

EXPOSE $PORT

CMD ["npm", "start"]