services:
  dev-service:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.dev.service
    develop:
      watch:
        - action: sync+restart
          path: ./.env
          target: /app/.env
        - action: rebuild
          path: ./pnpm-workspace.yaml
          target: /app/pnpm-workspace.yaml
    command: pnpm dev
    networks:
      - hmi_dev_network