FROM node:20-slim
ARG ServiceName

WORKDIR /app
COPY pnpm-workspace.yaml ./
RUN corepack enable
RUN corepack use pnpm 

WORKDIR /app/packages/global-types
COPY packages/global-types/package*.json ./
COPY packages/global-types ./

WORKDIR /app/packages/service
COPY packages/$ServiceName/package*.json ./
COPY packages/$ServiceName ./

WORKDIR /app
RUN pnpm install

WORKDIR /app/packages/service
