FROM node:20-slim AS build
WORKDIR /app
RUN corepack enable
RUN corepack use pnpm

COPY pnpm-*.yaml .

WORKDIR /app/libs/hmi-helper
COPY libs/hmi-helper .
RUN pnpm i

WORKDIR /app/packages/frontend
COPY packages/hmi-frontend .
RUN pnpm i
RUN pnpm build

FROM nginx:1.27.2-alpine AS base
COPY --from=build /app/packages/frontend/dist /usr/share/nginx/html
COPY nginx/env.sh /docker-entrypoint.d/env.sh
RUN chmod +x /docker-entrypoint.d/env.sh

CMD [ "nginx", "-g", "daemon off;" ]
