name: Publish All Services

on:
  schedule:
    - cron: "25 5 * * *"
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: hmi-frontend
      registry: ghcr.io

  build-streamer-server:
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: streamer-backend
      registry: ghcr.io

  build-waterfall-backend:
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: waterfall-backend
      registry: ghcr.io

  build-waterfall-streamer:
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: waterfall-streamer
      registry: ghcr.io

  build-game:
    uses: ./.github/workflows/publish-game.yml
    with:
      service_name: game
      registry: ghcr.io
