# .github/workflows/publish-all-services.yml
name: Publish All Services

on:
  schedule:
    - cron: "25 5 * * *"
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ${{github.repository_owner}}/hmi-frontend
            context: .
            dockerfile: .docker/Dockerfile.frontend

          - image: ${{github.repository_owner}}/streamer-server
            context: .
            dockerfile: .docker/Dockerfile.streamer
            build-args: VideoURL=https://ia601707.us.archive.org/4/items/4k-football-juventus-vs-tottenham-dolby-atmos/4kFootball%20Juventus%20vs%20Tottenham%20Dolby%20Atmos.mp4

          - image: ${{github.repository_owner}}/waterfall-backend
            context: .
            dockerfile: .docker/Dockerfile.prod.service
            build-args: ServiceName=waterfall-backend

          - image: ${{github.repository_owner}}/waterfall-streamer
            context: .
            dockerfile: .docker/Dockerfile.prod.service
            build-args: ServiceName=waterfall-streamer

          - image: ${{github.repository_owner}}/game-server
            context: .
            dockerfile: .docker/Dockerfile.game-server

    steps:
      - name: Checkout repositroy
        uses: actions/checkout@v4

      - name: Repo owner name to lowercase
        id: owner_name_lowercase
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extreact metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{matrix.image}}
          flavor: |
            latest=${{ github.event_name != 'pull_request' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{matrix.context}}
          file: ${{matrix.dockerfile}}
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          build-args: ${{matrix.build-args}}
