# .github/workflows/publish-all-services.yml
name: Publish All Services

on:
  schedule:
    - cron: "25 5 * * *"
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  docker-setup:
    uses: ./.github/workflows/docker-setup.yml

  build-frontend:
    needs: docker-setup
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: hmi-frontend
      registry: ghcr.io

  build-streamer-server:
    needs: docker-setup
    uses: ./.github/workflows/publish-streamer.yml
    with:
      service_name: streamer-backend
      registry: ghcr.io

  build-waterfall-backend:
    needs: docker-setup
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: waterfall-backend
      registry: ghcr.io

  build-waterfall-streamer:
    needs: docker-setup
    uses: ./.github/workflows/publish-service.yml
    with:
      service_name: waterfall-streamer
      registry: ghcr.io

  build-game:
    needs: docker-setup
    uses: ./.github/workflows/publish-game.yml
    with:
      service_name: game
      registry: ghcr.io
